spring.application.name=cafeland-club-backend


spring.datasource.url=jdbc:postgresql://localhost:5433/cafeland_club
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true