-- Esquema portable de cafeland_club
-- Ejecutar conectado a una base de datos nueva llamada cafeland_club.

BEGIN;

CREATE TABLE public.rangos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre character varying(30) NOT NULL,
    CONSTRAINT rangos_nombre_unique UNIQUE (nombre)
);

CREATE TABLE public.ligas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    minimo_puntos_torneo integer NOT NULL,
    numero integer NOT NULL,
    CONSTRAINT ligas_numero_unique UNIQUE (numero)
);

CREATE TABLE public.miembros (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado character varying(10) NOT NULL,
    fecha_ingreso date NOT NULL,
    nombre character varying(255) NOT NULL,
    rango_id bigint NOT NULL,
    nombre_normalizado character varying(255)
        GENERATED ALWAYS AS (lower(nombre::text)) STORED,
    CONSTRAINT miembros_estado_check
        CHECK (estado::text = ANY (ARRAY['ACTIVO'::text, 'INACTIVO'::text])),
    CONSTRAINT miembros_nombre_normalizado_unique UNIQUE (nombre_normalizado),
    CONSTRAINT miembros_rango_fk FOREIGN KEY (rango_id)
        REFERENCES public.rangos (id)
);

CREATE TABLE public.semanas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_fin date NOT NULL,
    fecha_inicio date NOT NULL,
    liga_id bigint NOT NULL,
    numero_semana integer NOT NULL,
    CONSTRAINT semanas_fechas_unique UNIQUE (fecha_inicio, fecha_fin),
    CONSTRAINT semanas_numero_unique UNIQUE (numero_semana),
    CONSTRAINT semanas_liga_fk FOREIGN KEY (liga_id)
        REFERENCES public.ligas (id)
);

CREATE TABLE public.resultados_semanales (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    puntos_desafio integer NOT NULL,
    puntos_torneo integer NOT NULL,
    miembro_id bigint NOT NULL,
    semana_id bigint NOT NULL,
    CONSTRAINT resultados_miembro_semana_unique UNIQUE (miembro_id, semana_id),
    CONSTRAINT resultados_miembro_fk FOREIGN KEY (miembro_id)
        REFERENCES public.miembros (id),
    CONSTRAINT resultados_semana_fk FOREIGN KEY (semana_id)
        REFERENCES public.semanas (id)
);

COMMIT;
